services:
  postgres:
    image: nuvix/postgres:18.1
    restart: unless-stopped

    env_file:
      - .env
    ports:
      - "${NUVIX_DATABASE_PORT:-5432}:5432"
      
    environment:
      POSTGRES_PASSWORD: ${NUVIX_DATABASE_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - nuvix

  redis:
    image: redis:8.6
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--requirepass", "${NUVIX_REDIS_PASSWORD}"]

    env_file:
      - .env
    environment:
      REDIS_PASSWORD: ${NUVIX_REDIS_PASSWORD}

    volumes:
      - ./configs/redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data

    restart: unless-stopped
    networks:
      - nuvix

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


  server:
    image: nuvix/server:latest

    env_file:
      - .env

    environment:
      NODE_ENV: production
      NUVIX_DATABASE_HOST: postgres
      NUVIX_REDIS_HOST: redis
      NUVIX_DATABASE_PORT: 5432

    ports:
      - "${NUVIX_API_PORT:-4000}:${NUVIX_API_PORT:-4000}"

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

    volumes:
      - nuvix_storage:/app/storage

    networks:
      - nuvix
    restart: unless-stopped


  platform:
    image: nuvix/platform:latest

    env_file:
      - .env

    environment:
      NODE_ENV: production
      NUVIX_DATABASE_HOST: postgres
      NUVIX_REDIS_HOST: redis
      NUVIX_DATABASE_PORT: 5432

    ports:
      - "${NUVIX_CONSOLE_API_PORT:-4100}:${NUVIX_CONSOLE_API_PORT:-4100}"

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

    networks:
      - nuvix
    restart: unless-stopped


  console:
    image: nuvix/console:latest

    ports:
      - "${NUVIX_CONSOLE_PORT:-3000}:3000"
    env_file:
    - .env

    depends_on:
      platform:
        condition: service_started

    networks:
      - nuvix
    restart: unless-stopped


volumes:
  postgres_data:
  redis_data:
  nuvix_storage:

networks:
  nuvix:
    driver: bridge
